"""
Extract Hebrew finite-verb lemma pairs from the verse-keyed hendiadys
lexicon (data/syntax-reference/hendiadys-lexicon.tsv). For each lexicon
verse with figure ∈ {hendiadys, doublet}, walk Macula's leaf-clauses on
the verse, identify the two clauses with finite-verb heads, extract the
(lemma_a, lemma_b) pair, output as a closed-list usable by Hpar as a
direct suppression mask.

Output: validators/_shared/hendiadys_lemma_pairs.py — frozenset of
sorted-pair tuples (lemma_a, lemma_b).

Usage:
    PYTHONIOENCODING=utf-8 py -3 scripts/extract_hendiadys_lemma_pairs.py
    PYTHONIOENCODING=utf-8 py -3 scripts/extract_hendiadys_lemma_pairs.py --figure hendiadys
"""
import argparse
import csv
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "validators"))

from validators._shared import macula_constituents as MC
from validators.colometry.validate_parallel_clause_split import (
    _is_leaf_clause, _clause_head_verb,
)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--figure", default="hendiadys,doublet",
                    help="Comma-separated figure types to extract (default: hendiadys,doublet)")
    ap.add_argument("--out", default=None,
                    help="Output Python file path (default: stdout)")
    ap.add_argument("--csv", action="store_true", help="CSV output for inspection")
    args = ap.parse_args()

    target_figures = {f.strip() for f in args.figure.split(",")}

    pairs: Counter = Counter()
    misses = 0
    no_clauses = 0
    seen_verses = 0

    lexicon_path = REPO_ROOT / "data" / "syntax-reference" / "hendiadys-lexicon.tsv"
    with lexicon_path.open(encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            if row["figure"] not in target_figures:
                continue
            seen_verses += 1
            book_slug = row["book"]
            chapter = int(row["chapter"])
            verse = int(row["verse"])
            try:
                vclauses = MC.get_verse_clauses(book_slug, chapter, verse)
            except Exception:
                misses += 1
                continue
            if not vclauses:
                no_clauses += 1
                continue
            leaves = [c for c in vclauses if _is_leaf_clause(c)]
            heads = []
            for cl in leaves:
                h = _clause_head_verb(cl)
                if h is None or h.lemma is None:
                    continue
                heads.append(h)
            if len(heads) < 2:
                no_clauses += 1
                continue
            # Extract all unordered pairs of head lemmas (n choose 2)
            for i, h1 in enumerate(heads):
                for h2 in heads[i + 1:]:
                    if h1.lemma == h2.lemma:
                        continue  # exact-lemma identical (already a separate guard)
                    pair = tuple(sorted([h1.lemma, h2.lemma]))
                    pairs[pair] += 1

    if args.csv:
        sys.stdout.reconfigure(encoding="utf-8")
        for pair, count in pairs.most_common():
            print(f"{pair[0]}\t{pair[1]}\t{count}")
        return

    # Default Python-output mode
    out_lines = [
        '"""Hebrew bonded-pair (hendiadys / doublet) verb-lemma index.',
        "",
        f"Auto-extracted from data/syntax-reference/hendiadys-lexicon.tsv",
        f"({sum(pairs.values())} pair-instances across {seen_verses} verses).",
        "",
        "Generated by scripts/extract_hendiadys_lemma_pairs.py — do not hand-edit.",
        "Re-run if the source lexicon changes.",
        '"""',
        "",
        "BONDED_LEMMA_PAIRS = frozenset({",
    ]
    for pair, count in pairs.most_common():
        out_lines.append(f'    ({pair[0]!r}, {pair[1]!r}),  # n={count}')
    out_lines.append("})")
    out_lines.append("")

    out_text = "\n".join(out_lines)
    if args.out:
        Path(args.out).write_text(out_text, encoding="utf-8")
    else:
        print(f"# {seen_verses} verses processed; {len(pairs)} unique pairs; "
              f"{misses} macula-load misses; {no_clauses} verses without ≥2 finite-verb leaves")
        print(out_text)


if __name__ == "__main__":
    main()
